### ISSUE TITLE
Failed scenarios are not re-running

### ISSUE THREAD

**Issue by AniruddhSolanki** [sugatmankar/cucumber-jvm-parallel-plugin-rerun-example#1]
following is the pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>Demo-Cucumber</groupId>
    <artifactId>Demo-Cucumber</artifactId>
    <version>1.0</version>

```
<dependencies>
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>2.53.0</version>
    </dependency>

    <dependency>
        <groupId>info.cukes</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>1.2.4-SNAPSHOT</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>info.cukes</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>1.2.4</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>info.cukes</groupId>
        <artifactId>cucumber-junit</artifactId>
        <version>1.2.4</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.relevantcodes</groupId>
        <artifactId>extentreports</artifactId>
        <version>2.41.0</version>
    </dependency>
    <!-- <repository> <id>sonatype-snapshots</id> <url>https://oss.sonatype.org/content/repositories/snapshots</url> 
        <snapshots> <enabled>true</enabled> </snapshots> </repository> -->
    <dependency>
        <groupId>com.github.temyers</groupId>
        <artifactId>cucumber-jvm-parallel-plugin</artifactId>
        <version>1.2.1</version>
    </dependency>
</dependencies>
<build>
    <plugins>
        <plugin>
            <groupId>com.github.temyers</groupId>
            <artifactId>cucumber-jvm-parallel-plugin</artifactId>
            <version>1.2.1</version>
            <executions>
                <execution>
                    <id>generateRunners</id>
                    <phase>validate</phase>
                    <goals>
                        <goal>generateRunners</goal>
                    </goals>
                    <configuration>
                        <!-- Mandatory -->
                        <!-- comma separated list of package names to scan for glue code -->
                        <glue>stepDefinitions</glue>
                        <!-- These are the default values -->
                        <!-- Where to output the generated tests -->
                        <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                        <!-- The diectory, which must be in the root of the runtime classpath, 
                            containing your feature files. -->
                        <featuresDirectory>src/test/resources/features/</featuresDirectory>
                        <!-- Directory where the cucumber report files shall be written -->
                        <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                        <!-- comma separated list of output formats -->
                        <format>json,html,rerun</format>
                        <!-- CucumberOptions.strict property -->
                        <strict>true</strict>
                        <!-- CucumberOptions.monochrome property -->
                        <monochrome>true</monochrome>
                        <!-- The tags to run, maps to CucumberOptions.tags property -->
                        <tags>"@Login"</tags>
                        <!-- If set to true, only feature files containing the required tags 
                            shall be generated. -->
                        <!-- Excluded tags (~@notMe) are ignored. -->
                        <filterFeaturesByTags>false</filterFeaturesByTags>
                        <!-- Generate TestNG runners instead of JUnit ones. -->
                        <useTestNG>false</useTestNG>
                        <!-- The naming scheme to use for the generated test classes. One 
                            of 'simple' or 'feature-title' -->
                        <namingScheme>simple</namingScheme>
                        <!-- The class naming pattern to use. Only required/used if naming 
                            scheme is 'pattern'. -->
                        <namingPattern>Parallel{c}IT</namingPattern>
                        <useJUnitReRun>true</useJUnitReRun>
                        <retryCount>2</retryCount>

                    </configuration>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.19</version>
            <configuration>
                <additionalClasspathElements>
                    <additionalClasspathElement>resources</additionalClasspathElement>
                </additionalClasspathElements>
                <forkCount>5</forkCount>
                <reuseForks>true</reuseForks>
                <includes>
                    <include>**/*IT.class</include>
                </includes>

            </configuration>
        </plugin>
    </plugins>
    <pluginManagement>
        <plugins>
            <!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
            <plugin>
                <groupId>org.eclipse.m2e</groupId>
                <artifactId>lifecycle-mapping</artifactId>
                <version>1.0.0</version>
                <configuration>
                    <lifecycleMappingMetadata>
                        <pluginExecutions>
                            <pluginExecution>
                                <pluginExecutionFilter>
                                    <groupId>
                                        com.github.temyers
                                    </groupId>
                                    <artifactId>
                                        cucumber-jvm-parallel-plugin
                                    </artifactId>
                                    <versionRange>
                                        [1.2.1,)
                                    </versionRange>
                                    <goals>
                                        <goal>generateRunners</goal>
                                    </goals>
                                </pluginExecutionFilter>
                                <action>
                                    <ignore></ignore>
                                </action>
                            </pluginExecution>
                        </pluginExecutions>
                    </lifecycleMappingMetadata>
                </configuration>
            </plugin>
        </plugins>
    </pluginManagement>
</build>
```

</project>
`
and following is stack trace.
`-------------------------------------------------------
##  T E S T S

Running Parallel01IT
@Login
Feature: Login Page

  @Login
  Scenario Outline: Validate login page         # features/login.feature:5
    Given I open <URL>
    When I enter <UserName> AND click on Next
    Then I enter <Password> AND click on SignIn

```
#And I should be logged in
Examples:
```

  @Login
  Scenario Outline: Validate login page           # features/login.feature:13
    Given I open https://mail.google.com          # loginPageStep.OpenURL(String
)
      junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at stepDefinitions.loginPageStep.OpenURL(loginPageStep.java:39)
        at ?.Given I open https://mail.google.com(features/login.feature:6)

```
When I enter aniruddh271290 AND click on Next # loginPageStep.enterUserName(
```

String)
    Then I enter  AND click on SignIn   # loginPageStep.signIn(String)

Failed scenarios:
features/login.feature:13 # Scenario Outline: Validate login page

1 Scenarios (1 failed)
3 Steps (1 failed, 2 skipped)
0m9.986s

junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at stepDefinitions.loginPageStep.OpenURL(loginPageStep.java:39)
        at ?.Given I open https://mail.google.com(features/login.feature:6)

Tests run: 4, Failures: 2, Errors: 0, Skipped: 2, Time elapsed: 10.802 sec <<< F
AILURE! - in Parallel01IT
Given I open https://mail.google.com(| https://mail.google.com | |)  Time elapsed: 0.01 sec  <<< FAILURE!
junit.framework.AssertionFailedError

| https://mail.google.com | |  Time elapsed: 0.012 s
ec  <<< FAILURE!
junit.framework.AssertionFailedError

Results :

Failed tests:
  null
  null

Tests run: 4, Failures: 2, Errors: 0, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.864 s
[INFO] Finished at: 2016-06-25T20:09:19+05:30
[INFO] Final Memory: 19M/140M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
19:test (default-test) on project Demo-Cucumber: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\admin\workspace\Demo-cucumber\target\surefire-r
eports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
C:\Users\admin\workspace\Demo-cucumber>mvn clean verify`

and then nothing happens.
I am not sure why stack trace shows Failed tests : Null

please help

**Comment by sugatmankar** [comment]
@Aniruddh 
1.2.1 version does not have functionality to re-run. It will be merge soon. Wait for sometime.

**Comment by AniruddhSolanki** [comment]
Any idea, How long will take?

**Comment by sugatmankar** [comment]
Wait for this week or next .

**Comment by AniruddhSolanki** [comment]
Hi sugat,

Is new version available now?

**Comment by sugatmankar** [comment]
@AniruddhSolanki  please check comments here 
https://github.com/temyers/cucumber-jvm-parallel-plugin/pull/53# 

 I'd recommend forking @sugatmankar https://github.com/sugatmankar/cucumber-jvm-parallel-plugin/tree/tagwiseOutlinewiseIssueRerun repository to build and test.

**Comment by AniruddhSolanki** [comment]
Found the solution. 
http://mkolisnyk.github.io/cucumber-reports/extended-cucumber-runner

**Comment by Bhala-Voyanta** [comment]
http://mkolisnyk.github.io/cucumber-reports/extended-cucumber-runner

**Comment by Bhala-Voyanta** [comment]
@AniruddhSolanki 
Found the solution.
http://mkolisnyk.github.io/cucumber-reports/extended-cucumber-runner
For my project on JUnit, the above solution doesn't help.
Am using the following:
1. Java
2. Cucumber
3. Maven
4. Jenkins

Can you please help me in just rerunning only the failed scenarios and finally the cucumber report should show only the latest run report
